create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text not null,
  preferred_contact text not null default 'Call',
  services text[] not null default '{}',
  message text,
  utm jsonb not null default '{}'::jsonb,
  photos jsonb not null default '[]'::jsonb,
  source text not null default 'website_contact_form',
  submitted_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.leads enable row level security;

drop policy if exists "Allow public lead inserts" on public.leads;

create policy "Allow public lead inserts"
  on public.leads
  for insert
  to anon, authenticated
  with check (true);
